### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by billi95** [NYT92/mrm-downloader#1]
When trying to use it I get a pop up with the following error "An error occurred while creating the ZIP file. Please check the console for details."
When opening the console on google chrome I get this error:
```text
userscript.html?name=MRM-Downloader.user.js&id=135ca830-47bf-4588-9aa2-e8d2e5867b03:156 Error processing https://i5.myreadingmanga.info/images/2022/06/25/Trailer-Page_7-c0.jpg: TypeError: Cannot read properties of null (reading '1')
    at Object.onload (userscript.html?name=MRM-Downloader.user.js&id=135ca830-47bf-4588-9aa2-e8d2e5867b03:147:124)
    at Pt (<anonymous>:10:89)
    at <anonymous>:46:242
    at Pt (<anonymous>:10:89)
    at r (<anonymous>:32:484)
    at <anonymous>:33:112
    at <anonymous>:22:300
    at _ (<anonymous>:22:319)
```

**Comment by NYT92** [comment]
Have you tried to allow all the domain from i[1-6].myreadingmanga.info yet? If already but still got an error maybe try to reinstalling the script. I will check the issue if the issue still happening...

**Comment by billi95** [comment]
> Have you tried to click always allow on one of these domain from i[1-6].myreadingmanga.info yet?

not sure what that means. if it is not in the manual then no. I followed the instructions as written nothing else.

**Comment by NYT92** [comment]
I have now fixed the issue, can you try it again? let me know

**Comment by billi95** [comment]
yep works fine for me now

**Comment by NYT92** [comment]
It's good to know also that ad-provider.js stuff is an ad script and you should probably ignore it. I will make some changes to the script if the issue still occurs often and add more feature to it.
